parameters:

services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\CustomExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    App\Adapter\PaypalPaymentProcessorAdapter:
        tags:
            - { name: 'app.payment_provider', key: 'paypal' }
        arguments:
            - !service
                class: Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor

    App\Adapter\StripePaymentProcessorAdapter:
        tags:
            - { name: 'app.payment_provider', key: 'stripe' }
        arguments:
            - !service
                class: Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor

    App\Registry\PaymentProcessorRegistry:
        arguments:
            $locator: !tagged_locator
                tag: 'app.payment_provider'
                index_by: 'key'